id: IE976EC81
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T07:11:24+00:00'
last_modified: '2022-06-08T01:05:54.769135+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ58511
  title: མདོ་སྡེ་བསྐལ་བཟང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2644':
      image_group_id: I4CZ58826
      title: ''
      total_pages: 1045
      order: 1
      base_file: 2644.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
